config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'base#index'
    resources :people

    namespace :businesses do
      resources :verifications
    end
  end

  get '/login', to: 'auth/sessions#new'
  get '/logout', to: 'auth/sessions#destroy'
  get '/register', to: 'auth/registrations#new'

  namespace :auth do
    resources :sessions, only: [:new, :create, :destroy]
    resources :registrations, only: [:new, :create]
  end

  get 'open-a-business', to: 'public/businesses#new', as: 'open_a_business'

  scope module: "public" do

    resources :products, only: [:index, :show]

    resources :businesses do
      resources :products, only: [ :index, :show, :edit]

      namespace :merchant do
        root 'orders#index'

        resources :products
        resources :orders
        resources :reports

        resources :banks
        resources :withdrawals

        resources :conversations
      end
    end

    resources :people do

      resources :favorites
      resources :collections
      resources :networks
      resources :friendships

      resources :carts
      resources :orders
      resources :subscriptions

      resources :wallets
      resources :rewards

      resources :deposits
      resources :withdraws

      resources :conversations
    end

    resources :favorites

  end

  namespace :search do
    resources :people
  end

  post '/billplz/callback', to: 'public/deposits#create'
  get '/join/:sponsor_token', to: 'public/welcome#index'
  root 'public/welcome#index'
end

app/views/layouts/shared/_nav_bottom.html.haml
.navbar.navbar-default.navbar-fixed-bottom.footer
  .footer-boxed.text-muted
    %ul.nav.navbar-nav.visible-xs-block
      %li
        %a.text-center.collapsed{"data-target" => "#footer", "data-toggle" => "collapse"}
          %i.icon-circle-up2
    #footer.navbar-collapse.collapse
      .navbar-text
        &copy; 2016 Atlantis. All Rights Reserved.
      .navbar-right
        %ul.nav.navbar-nav
          %li
            = link_to "About", "/pages/about"
          %li
            = link_to "Terms & Conditions", "/pages/about"
          %li
            = link_to "Privacy Policy", "/pages/about"
          %li
            = link_to "Contact Us", "/pages/about"
          %li
            = link_to "FAQ", "/pages/faq"

app/views/layouts/shared/_nav_main.html.haml
/ Second navbar
#navbar-second.navbar.navbar-default
  .navbar-boxed
    %ul.nav.navbar-nav.no-border.visible-xs-block
      %li
        %a.text-center.collapsed{"data-target" => "#navbar-second-toggle", "data-toggle" => "collapse"}
          %i.icon-menu7
    #navbar-second-toggle.navbar-collapse.collapse
      %ul.nav.navbar-nav

        %li
          = link_to root_path do
            %i.icon-home.position-left
            Home
        %li
          = link_to products_path do
            %i.icon-file-empty.position-left
            Products

        = render partial: "layouts/shared/nav_main/categories"

        %li
          = link_to businesses_path do
            %i.icon-store2.position-left
            Businesses

        = render partial: "layouts/shared/nav_main/lists"

        %li
          = link_to search_people_path do
            %i.icon-users4.position-left
            People

      = render partial: "layouts/shared/nav_main/right"

app/views/layouts/shared/_nav_top.html.haml
/ Main navbar
.navbar.navbar-inverse.bg-atlantis
  .navbar-boxed
    .navbar-header
      = link_to root_path, class: 'navbar-brand' do
        = image_tag 'atlantis_logo.png', alt: 'We make life happening'

      %ul.nav.navbar-nav.visible-xs-block
        %li
          %a{"data-target" => "#navbar-mobile", "data-toggle" => "collapse"}
            %i.icon-tree5
        %li
          %a.sidebar-mobile-main-toggle
            %i.icon-paragraph-justify3

    #navbar-mobile.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li
          %a.sidebar-control.sidebar-main-toggle.hidden-xs
            %i.icon-paragraph-justify3
        %li
          = link_to products_path do
            %i.icon-search4
            %span.visible-xs-inline-block.position-right Search

      %ul.nav.navbar-nav.navbar-right

        - if current_person

          = render partial: 'layouts/shared/nav_top/usernav'

        - else

          %li
            = link_to "Register", register_path

          %li
            = link_to "Log In", login_path

app/views/layouts/shared/_nav_top.tmp.haml
/ Main navbar
.navbar.navbar-inverse.bg-atlantis
  .navbar-boxed
    .navbar-header
      = link_to root_path, class: 'navbar-brand' do
        = image_tag 'atlantis_shop.png', alt: 'We make life happening'

      %ul.nav.navbar-nav.visible-xs-block
        %li
          %a{"data-target" => "#navbar-mobile", "data-toggle" => "collapse"}
            %i.icon-tree5
        %li
          %a.sidebar-mobile-main-toggle
            %i.icon-paragraph-justify3
    #navbar-mobile.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li
          %a.sidebar-control.sidebar-main-toggle.hidden-xs
            %i.icon-paragraph-justify3
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "/"}
            %i.icon-git-compare
            %span.visible-xs-inline-block.position-right Git updates
            %span.badge.bg-warning-400 9
          .dropdown-menu.dropdown-content
            .dropdown-content-heading
              Git updates
              %ul.icons-list
                %li
                  %a{:href => "/"}
                    %i.icon-sync
            %ul.media-list.dropdown-content-body.width-350
              %li.media
                .media-left
                  %a.btn.border-primary.text-primary.btn-flat.btn-rounded.btn-icon.btn-sm{:href => "/"}
                    %i.icon-git-pull-request
                .media-body
                  Drop the IE
                  %a{:href => "/"} specific hacks
                  for temporal inputs
                  .media-annotation 4 minutes ago
              %li.media
                .media-left
                  %a.btn.border-warning.text-warning.btn-flat.btn-rounded.btn-icon.btn-sm{:href => "/"}
                    %i.icon-git-commit
                .media-body
                  Add full font overrides for popovers and tooltips
                  .media-annotation 36 minutes ago
              %li.media
                .media-left
                  %a.btn.border-info.text-info.btn-flat.btn-rounded.btn-icon.btn-sm{:href => "/"}
                    %i.icon-git-branch
                .media-body
                  %a{:href => "/"} Chris Arney
                  created a new
                  %span.text-semibold Design
                  branch
                  .media-annotation 2 hours ago
              %li.media
                .media-left
                  %a.btn.border-success.text-success.btn-flat.btn-rounded.btn-icon.btn-sm{:href => "/"}
                    %i.icon-git-merge
                .media-body
                  %a{:href => "/"} Eugene Kopyov
                  merged
                  %span.text-semibold Master
                  and
                  %span.text-semibold Dev
                  branches
                  .media-annotation Dec 18, 18:36
              %li.media
                .media-left
                  %a.btn.border-primary.text-primary.btn-flat.btn-rounded.btn-icon.btn-sm{:href => "/"}
                    %i.icon-git-pull-request
                .media-body
                  Have Carousel ignore keyboard events
                  .media-annotation Dec 12, 05:46
            .dropdown-content-footer
              %a{"data-popup" => "tooltip", :href => "/", :title => "All activity"}
                %i.icon-menu.display-block
      %p.navbar-text
        %span.label.bg-success-400 Online
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown.language-switch
          %a.dropdown-toggle{"data-toggle" => "dropdown"}
            %img.position-left{:alt => "", :src => "/assets/images/flags/gb.png"}/
            English
            %span.caret
          %ul.dropdown-menu
            %li
              %a.deutsch
                %img{:alt => "", :src => "/assets/images/flags/de.png"}/
                Deutsch
            %li
              %a.ukrainian
                %img{:alt => "", :src => "/assets/images/flags/ua.png"}/
                Українська
            %li
              %a.english
                %img{:alt => "", :src => "/assets/images/flags/gb.png"}/
                English
            %li
              %a.espana
                %img{:alt => "", :src => "/assets/images/flags/es.png"}/
                España
            %li
              %a.russian
                %img{:alt => "", :src => "/assets/images/flags/ru.png"}/
                Русский
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "/"}
            %i.icon-bubbles4
            %span.visible-xs-inline-block.position-right Messages
            %span.badge.bg-warning-400 2
          .dropdown-menu.dropdown-content.width-350
            .dropdown-content-heading
              Messages
              %ul.icons-list
                %li
                  %a{:href => "/"}
                    %i.icon-compose
            %ul.media-list.dropdown-content-body
              %li.media
                .media-left
                  = image_tag "default_person_avatar.png", class: "img-circle img-sm"
                  %span.badge.bg-danger-400.media-badge 5
                .media-body
                  %a.media-heading{:href => "/"}
                    %span.text-semibold James Alexander
                    %span.media-annotation.pull-right 04:58
                  %span.text-muted who knows, maybe that would be the best thing for me...
              %li.media
                .media-left
                  = image_tag "default_person_avatar.png", class: "img-circle img-sm"
                  %span.badge.bg-danger-400.media-badge 4
                .media-body
                  %a.media-heading{:href => "/"}
                    %span.text-semibold Margo Baker
                    %span.media-annotation.pull-right 12:16
                  %span.text-muted That was something he was unable to do because...
              %li.media
                .media-left
                  = image_tag "default_person_avatar.png", class: "img-circle img-sm"
                .media-body
                  %a.media-heading{:href => "/"}
                    %span.text-semibold Jeremy Victorino
                    %span.media-annotation.pull-right 22:48
                  %span.text-muted But that would be extremely strained and suspicious...
              %li.media
                .media-left
                  = image_tag "default_person_avatar.png", class: "img-circle img-sm"
                .media-body
                  %a.media-heading{:href => "/"}
                    %span.text-semibold Beatrix Diaz
                    %span.media-annotation.pull-right Tue
                  %span.text-muted What a strenuous career it is that I've chosen...
              %li.media
                .media-left
                  = image_tag "default_person_avatar.png", class: "img-circle img-sm"
                .media-body
                  %a.media-heading{:href => "/"}
                    %span.text-semibold Richard Vango
                    %span.media-annotation.pull-right Mon
                  %span.text-muted Other travelling salesmen live a life of luxury...
            .dropdown-content-footer
              %a{"data-popup" => "tooltip", :href => "/", :title => "All messages"}
                %i.icon-menu.display-block

        %li.dropdown.dropdown-user
          %a.dropdown-toggle{"data-toggle" => "dropdown"}
            = image_tag "default_person_avatar.png"
            %span JinKang
            %i.caret
          %ul.dropdown-menu.dropdown-menu-right
            %li
              %a{:href => "/"}
                %i.icon-user-plus
                My profile
            %li
              %a{:href => "/"}
                %i.icon-coins
                My balance
            %li
              %a{:href => "/"}
                %span.badge.bg-teal-400.pull-right 58
                %i.icon-comment-discussion
                Messages
            %li.divider
            %li
              %a{:href => "/"}
                %i.icon-cog5
                Account settings
            %li
              %a{:href => "/"}
                %i.icon-switch2
                Logout
/ /main navbar

app/views/layouts/shared/_sidebar.html.haml
/ Main sidebar
.sidebar.sidebar-main.sidebar-default
  .sidebar-content
    / Title
    .category-title.h6
      %span Components
      %ul.icons-list
        %li
          %a{:href => "boxed_default.html#"}
            %i.icon-gear
    / /title
    / Search task
    .sidebar-category
      .category-title
        %span Search task
        %ul.icons-list
          %li
            %a{"data-action" => "collapse", :href => "boxed_default.html#"}
      .category-content
        %form{:action => "boxed_default.html#"}
          .has-feedback.has-feedback-left
            %input.form-control{:placeholder => "Type and hit Enter", :type => "search"}/
            .form-control-feedback
              %i.icon-search4.text-size-base.text-muted
    / /search task
    / Action buttons
    .sidebar-category
      .category-title
        %span Action buttons
        %ul.icons-list
          %li
            %a{"data-action" => "collapse", :href => "boxed_default.html#"}
      .category-content
        .row
          .col-xs-6
            %button.btn.bg-teal-400.btn-block.btn-float.btn-float-lg{:type => "button"}
              %i.icon-git-branch
              %span Branch
            %button.btn.bg-purple-300.btn-block.btn-float.btn-float-lg{:type => "button"}
              %i.icon-mail-read
              %span Messages
          .col-xs-6
            %button.btn.bg-warning-400.btn-block.btn-float.btn-float-lg{:type => "button"}
              %i.icon-stats-bars
              %span Statistics
            %button.btn.bg-blue.btn-block.btn-float.btn-float-lg{:type => "button"}
              %i.icon-people
              %span Users
    / /action buttons
    / Task navigation
    .sidebar-category.sidebar-category-visible
      .category-title
        %span Navigation
        %ul.icons-list
          %li
            %a{"data-action" => "collapse", :href => "boxed_default.html#"}
      .category-content.no-padding
        %ul.navigation.navigation-main.navigation-accordion
          %li.navigation-header
            %span Actions
            %i.icon-menu{:title => "Actions"}
          %li
            %a{:href => "boxed_default.html#"}
              %i.icon-googleplus5
              %span Create task
          %li
            %a{:href => "boxed_default.html#"}
              %i.icon-portfolio
              %span Create project
          %li
            %a{:href => "boxed_default.html#"}
              %i.icon-compose
              %span Edit task list
          %li
            %a{:href => "boxed_default.html#"}
              %i.icon-user-plus
              %span
                Assign users
                %span.label.label-success 94 online
          %li
            %a{:href => "boxed_default.html#"}
              %i.icon-collaboration
              %span Create team
          %li.navigation-header
            %span Tasks
            %i.icon-menu{:title => "Tasks"}
          %li
            %a{:href => "boxed_default.html#"}
              %i.icon-files-empty
              %span All tasks
          %li
            %a{:href => "boxed_default.html#"}
              %i.icon-file-plus
              %span
                Active tasks
                %span.badge.badge-default 28
          %li
            %a{:href => "boxed_default.html#"}
              %i.icon-file-check
              %span Closed tasks
          %li.navigation-divider
          %li
            %a{:href => "boxed_default.html#"}
              %i.icon-reading
              %span
                Assigned to me
                %span.badge.badge-info 86
          %li
            %a{:href => "boxed_default.html#"}
              %i.icon-make-group
              %span
                Assigned to my team
                %span.badge.badge-info 47
          %li
            %a{:href => "boxed_default.html#"}
              %i.icon-cog3
              %span Settings
    / /task navigation
    / Assigned users
    .sidebar-category
      .category-title
        %span Assigned users
        %ul.icons-list
          %li
            %a{"data-action" => "collapse", :href => "boxed_default.html#"}
      .category-content
        %ul.media-list
          %li.media
            %a.media-left{:href => "boxed_default.html#"}
              = image_tag "default_person_avatar.png", class: "img-circle img-sm"
            .media-body
              %a.media-heading.text-semibold{:href => "boxed_default.html#"} James Alexander
              %span.text-size-mini.text-muted.display-block Santa Ana, CA.
            .media-right.media-middle
              %span.status-mark.bg-success
          %li.media
            %a.media-left{:href => "boxed_default.html#"}
              = image_tag "default_person_avatar.png", class: "img-circle img-sm"
            .media-body
              %a.media-heading.text-semibold{:href => "boxed_default.html#"} Jeremy Victorino
              %span.text-size-mini.text-muted.display-block Dowagiac, MI.
            .media-right.media-middle
              %span.status-mark.bg-danger
          %li.media
            %a.media-left{:href => "boxed_default.html#"}
              = image_tag "default_person_avatar.png", class: "img-circle img-sm"
            .media-body
              %a.media-heading.text-semibold{:href => "boxed_default.html#"} Margo Baker
              %span.text-size-mini.text-muted.display-block Kasaan, AK.
            .media-right.media-middle
              %span.status-mark.bg-success
          %li.media
            %a.media-left{:href => "boxed_default.html#"}
              = image_tag "default_person_avatar.png", class: "img-circle img-sm"
            .media-body
              %a.media-heading.text-semibold{:href => "boxed_default.html#"} Beatrix Diaz
              %span.text-size-mini.text-muted.display-block Neenah, WI.
            .media-right.media-middle
              %span.status-mark.bg-warning
          %li.media
            %a.media-left{:href => "boxed_default.html#"}
              = image_tag "default_person_avatar.png", class: "img-circle img-sm"
            .media-body
              %a.media-heading.text-semibold{:href => "boxed_default.html#"} Richard Vango
              %span.text-size-mini.text-muted.display-block Grapevine, TX.
            .media-right.media-middle
              %span.status-mark.bg-grey-400
    / /assigned users
    / Revisions
    .sidebar-category
      .category-title
        %span Revisions
        %ul.icons-list
          %li
            %a{"data-action" => "collapse", :href => "boxed_default.html#"}
      .category-content
        %ul.media-list
          %li.media
            .media-left
              %a.btn.border-primary.text-primary.btn-flat.btn-rounded.btn-icon.btn-sm{:href => "boxed_default.html#"}
                %i.icon-git-pull-request
            .media-body
              Drop the IE
              %a{:href => "boxed_default.html#"} specific hacks
              for temporal inputs
              .media-annotation 4 minutes ago
          %li.media
            .media-left
              %a.btn.border-warning.text-warning.btn-flat.btn-rounded.btn-icon.btn-sm{:href => "boxed_default.html#"}
                %i.icon-git-commit
            .media-body
              Add full font overrides for popovers and tooltips
              .media-annotation 36 minutes ago
          %li.media
            .media-left
              %a.btn.border-info.text-info.btn-flat.btn-rounded.btn-icon.btn-sm{:href => "boxed_default.html#"}
                %i.icon-git-branch
            .media-body
              %a{:href => "boxed_default.html#"} Chris Arney
              created a new
              %span.text-semibold Design
              branch
              .media-annotation 2 hours ago
          %li.media
            .media-left
              %a.btn.border-success.text-success.btn-flat.btn-rounded.btn-icon.btn-sm{:href => "boxed_default.html#"}
                %i.icon-git-merge
            .media-body
              %a{:href => "boxed_default.html#"} Eugene Kopyov
              merged
              %span.text-semibold Master
              and
              %span.text-semibold Dev
              branches
              .media-annotation Dec 18, 18:36
          %li.media
            .media-left
              %a.btn.border-primary.text-primary.btn-flat.btn-rounded.btn-icon.btn-sm{:href => "boxed_default.html#"}
                %i.icon-git-pull-request
            .media-body
              Have Carousel ignore keyboard events
              .media-annotation Dec 12, 05:46
    / /revisions
    / Completeness stats
    .sidebar-category
      .category-title
        %span Completeness stats
        %ul.icons-list
          %li
            %a{"data-action" => "collapse", :href => "boxed_default.html#"}
      .category-content
        %ul.progress-list
          %li
            %label
              Highest priority
              %span 80%
            .progress.progress-xxs
              .progress-bar.progress-bar-danger{:style => "width: 80%"}
                %span.sr-only 80% Complete
          %li
            %label
              High priority
              %span 70%
            .progress.progress-xxs
              .progress-bar.progress-bar-info{:style => "width: 70%"}
                %span.sr-only 70% Complete
          %li
            %label
              Normal priority
              %span 50%
            .progress.progress-xxs
              .progress-bar.progress-bar-primary{:style => "width: 50%"}
                %span.sr-only 50% Complete
          %li
            %label
              Low prioruty
              %span 60%
            .progress.progress-xxs
              .progress-bar.progress-bar-success{:style => "width: 60%"}
                %span.sr-only 60% Complete
    / /completeness stats
/ /main sidebar