config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'base#index'
    resources :people

    namespace :businesses do
      resources :verifications
    end
  end

  get '/login', to: 'auth/sessions#new'
  get '/logout', to: 'auth/sessions#destroy'
  get '/register', to: 'auth/registrations#new'

  namespace :auth do
    resources :sessions, only: [:new, :create, :destroy]
    resources :registrations, only: [:new, :create]
  end

  get 'open-a-business', to: 'public/businesses#new', as: 'open_a_business'

  scope module: "public" do

    resources :products, only: [:index, :show]

    resources :businesses do
      resources :products, only: [ :index, :show, :edit]

      namespace :merchant do
        root 'orders#index'

        resources :products
        resources :orders
        resources :reports

        resources :banks
        resources :withdrawals

        resources :conversations
      end
    end

    resources :people do

      resources :favorites
      resources :collections
      resources :networks
      resources :friendships

      resources :carts
      resources :orders
      resources :subscriptions

      resources :wallets
      resources :rewards

      resources :deposits
      resources :withdraws

      resources :conversations
    end

    resources :favorites

  end

  namespace :search do
    resources :people
  end

  post '/billplz/callback', to: 'public/deposits#create'
  get '/join/:sponsor_token', to: 'public/welcome#index'
  root 'public/welcome#index'
end

app/views/layouts/shared/nav_main/_categories.html.haml
%li.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "boxed_default.html#"}
    %i.icon-stack.position-left
    Categories
    %span.caret
  %ul.dropdown-menu.width-250
    %li.dropdown-header Find product by category
    - navigate_by_category.each do |category|
      %li
        = link_to category.name, products_path(category_id: category)

app/views/layouts/shared/nav_main/_lists.html.haml
%li.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "boxed_default.html#"}
    %i.icon-make-group.position-left
    Listing
    %span.caret
  %ul.dropdown-menu.width-250
    %li.dropdown-header Find business by listing
    - navigate_by_list.each do |list|
      %li
        = link_to list.name, businesses_path(list_id: list)

app/views/layouts/shared/nav_main/_right.html.haml
- if current_person
  %ul.nav.navbar-nav.navbar-right
    %li.dropdown
      = link_to "javascript:;", class: "dropdown-toggle", data: { toggle: "dropdown"} do
        %i.icon-price-tag2.position-left
        Membership
        %span.label.label-inline.position-right.bg-slate-400= current_person.get_membership

    %li.dropdown
      = link_to "javascript:;", class: "dropdown-toggle", data: { toggle: "dropdown"} do
        %i.icon-wallet
        %span.visible-xs-inline-block.position-right Cash Management

      %ul.dropdown-menu.dropdown-menu-right
        %li
          = link_to new_person_deposit_path(current_person) do
            %i.icon-download
            Top up
        %li
          = link_to new_person_withdraw_path(current_person) do
            %i.icon-upload
            Cash out

app/views/layouts/shared/nav_main/_types.html.haml
%li.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "boxed_default.html#"}
    %i.icon-stack2.position-left
    Types
    %span.caret
  %ul.dropdown-menu.width-250
    %li.dropdown-header Find business by type
    - navigate_by_type.each do |type|
      %li
        = link_to type.name, "#{type.slug}"