config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'base#index'
    resources :people

    namespace :businesses do
      resources :verifications
    end
  end

  get '/login', to: 'auth/sessions#new'
  get '/logout', to: 'auth/sessions#destroy'
  get '/register', to: 'auth/registrations#new'

  namespace :auth do
    resources :sessions, only: [:new, :create, :destroy]
    resources :registrations, only: [:new, :create]
  end

  get 'open-a-business', to: 'public/businesses#new', as: 'open_a_business'

  scope module: "public" do

    resources :products, only: [:index, :show]

    resources :businesses do
      resources :products, only: [ :index, :show, :edit]

      namespace :merchant do
        root 'orders#index'

        resources :products
        resources :orders
        resources :reports

        resources :banks
        resources :withdrawals

        resources :conversations
      end
    end

    resources :people do

      resources :favorites
      resources :collections
      resources :networks
      resources :friendships

      resources :carts
      resources :orders
      resources :subscriptions

      resources :wallets
      resources :rewards

      resources :deposits
      resources :withdraws

      resources :conversations
    end

    resources :favorites

  end

  namespace :search do
    resources :people
  end

  post '/billplz/callback', to: 'public/deposits#create'
  get '/join/:sponsor_token', to: 'public/welcome#index'
  root 'public/welcome#index'
end

app/views/layouts/shared/sidebar/_admin.html.haml
.sidebar.sidebar-main.sidebar-default
  .sidebar-content

    .category-title.h6
      %span Site's Management

    .sidebar-category.sidebar-category-visible
      .category-content.no-padding
        %ul.navigation.navigation-main.navigation-accordion
          %li.navigation-header
            %span People
            %i.icon-menu{:title => "People"}
          %li
            = link_to admin_people_path do
              %i.icon-googleplus5
              %span Wait for verification
          %li
            = link_to "" do
              %i.icon-portfolio
              %span unknown action
          %li
            = link_to "" do
              %i.icon-portfolio
              %span unknown action

          %li.navigation-header
            %span Businesses
            %i.icon-menu{:title => "Merchants"}
          %li
            = link_to admin_businesses_verifications_path do
              %i.icon-portfolio
              %span Wait for verification
          %li
            = link_to "" do
              %i.icon-portfolio
              %span unknown action

          %li.navigation-header
            %span Others
            %i.icon-menu{:title => "Others"}

          %li
            = link_to "" do
              %i.icon-portfolio
              %span unknown action
          %li
            = link_to "" do
              %i.icon-portfolio
              %span unknown action

app/views/layouts/shared/sidebar/_categories.html.haml
.sidebar.sidebar-main.sidebar-default
  .sidebar-content

    .sidebar-category.sidebar-category-visible
      .category-content
        = form_tag products_path, method: "get", class: "heading-form" do
          .form-group.has-feedback
            = text_field_tag :search, params[:search], placeholder: "Search by name", type: "search", class: "form-control"
            .form-control-feedback
              %i.icon-search4.text-size-base.text-muted
      %br
      %br
      .clearfix

  .sidebar-content

    .category-title.h6
      %span Find by categories
      %ul.icons-list
        %li
          = link_to "javascript:;" do
            %i.icon-cogs

    .sidebar-category.sidebar-category-visible
      .category-content.no-padding
        %ul.navigation.navigation-main.navigation-accordion
          - navigate_by_category.each do |category|
            %li
              = link_to products_path(category_id: category) do
                %span= category.name

app/views/layouts/shared/sidebar/_merchant.html.haml
.sidebar.sidebar-main.sidebar-default
  .sidebar-content

    .category-title.h6
      %span MERCHANT MANAGEMENT

    .sidebar-category.sidebar-category-visible
      .category-content.no-padding
        %ul.navigation.navigation-main.navigation-accordion

          %li.navigation-header
            %span Merchant Activities
            %i.icon-menu{:title => "Merchant Activities"}
          %li
            - if params[:business_id]
              = link_to business_merchant_orders_path(params[:business_id]) do
                %i.icon-compose
                %span Orders
            - else
              = link_to business_merchant_orders_path(params[:id]) do
                %i.icon-compose
                %span Orders
          %li
            - if params[:business_id]
              = link_to business_merchant_products_path(params[:business_id]) do
                %i.icon-portfolio
                %span Products
            - else
              = link_to business_merchant_products_path(params[:id]) do
                %i.icon-portfolio
                %span Products

          %li.navigation-header
            %span Merchant Bank
            %i.icon-menu{:title => "Merchant Bank"}
          %li
            - if params[:business_id]
              = link_to business_merchant_banks_path(params[:business_id]) do
                %i.icon-coins
                %span Bank statements
            - else
              = link_to business_merchant_banks_path(params[:id]) do
                %i.icon-coins
                %span Bank statements
          %li
            - if params[:business_id]
              = link_to business_merchant_withdrawals_path(params[:business_id]) do
                %i.icon-database-export
                %span Withdrawals
            - else
              = link_to business_merchant_withdrawals_path(params[:id]) do
                %i.icon-database-export
                %span Withdrawals

          %li.navigation-divider
          %li
            - if params[:business_id]
              = link_to business_merchant_conversations_path(params[:business_id]) do
                %i.icon-bubbles4
                %span Conversations
            - else
              = link_to business_merchant_conversations_path(params[:id]) do
                %i.icon-bubbles4
                %span Conversations
          %li
            - if params[:business_id]
              = link_to edit_business_path(params[:business_id]) do
                %i.icon-cog5
                %span Account settings
            - else
              = link_to edit_business_path(params[:id]) do
                %i.icon-cog5
                %span Account settings

app/views/layouts/shared/sidebar/_people.html.haml
.sidebar.sidebar-main.sidebar-default
  .sidebar-content

    .category-title.h6
      %span My Management

    .sidebar-category.sidebar-category-visible
      .category-content.no-padding
        %ul.navigation.navigation-main.navigation-accordion
          %li.navigation-header
            %span MY ACTIVITIES
            %i.icon-menu{:title => "Actions"}
          %li
            = link_to person_path(current_person) do
              %i.icon-heart6
              %span Favorites
          %li
            = link_to person_collections_path(current_person) do
              %i.icon-drawer3
              %span Collections
          %li
            = link_to person_networks_path(current_person) do
              %i.icon-tree7
              %span Networks
          %li
            = link_to person_friendships_path(current_person) do
              %i.icon-users4
              %span Friends

          %li.navigation-header
            %span MY BILLING
            %i.icon-menu{:title => "Wallets"}

          %li
            = link_to person_carts_path(current_person) do
              %i.icon-cart5
              %span Shoping Cart

            %li
              = link_to person_orders_path(current_person) do
                %i.icon-compose
                %span Orders
          -# %li
          -#   = link_to person_subscriptions_path(current_person) do
          -#     %i.icon-price-tags2
          -#     %span Subscriptions

          %li.navigation-header
            %span MY WALLET
            %i.icon-menu{:title => "Wallets"}
          %li
            = link_to person_wallets_path(current_person) do
              %i.icon-coins
              %span Cash wallet
          %li
            = link_to person_rewards_path(current_person) do
              %i.icon-credit-card
              %span Reward point

          %li.navigation-divider
          %li
            = link_to person_conversations_path(current_person) do
              %i.icon-bubbles4
              %span Conversations
          %li
            = link_to edit_person_path(current_person) do
              %i.icon-cog5
              %span Account settings

app/views/layouts/shared/sidebar/_search_people.html.haml
.sidebar.sidebar-main.sidebar-default
  .sidebar-content

    .sidebar-category.sidebar-category-visible
      .category-content
        = form_tag search_people_path, method: "get", class: "heading-form" do
          .form-group.has-feedback
            = text_field_tag :search, params[:search], placeholder: "Search by name", type: "search", class: "form-control"
            .form-control-feedback
              %i.icon-search4.text-size-base.text-muted
      %br
      %br
      .clearfix

  .sidebar-content

    .category-title.h6
      %span Find by state
      %ul.icons-list

    .sidebar-category.sidebar-category-visible
      .category-content.no-padding
        %ul.navigation.navigation-main.navigation-accordion
          %li
            = link_to search_people_path(state: "Perlis") do
              %span Perlis
          %li
            = link_to search_people_path(state: "Kedah") do
              %span Kedah
          %li
            = link_to search_people_path(state: "Penang") do
              %span Penang
          %li
            = link_to search_people_path(state: "Perak") do
              %span Perak
          %li
            = link_to search_people_path(state: "Selangor") do
              %span Selangor
          %li
            = link_to search_people_path(state: "Negeri Sembilan") do
              %span Negeri Sembilan
          %li
            = link_to search_people_path(state: "Melaka") do
              %span Melaka
          %li
            = link_to search_people_path(state: "Johor") do
              %span Johor
          %li
            = link_to search_people_path(state: "Pahang") do
              %span Pahang
          %li
            = link_to search_people_path(state: "Terengganu") do
              %span Terengganu
          %li
            = link_to search_people_path(state: "Sabah") do
              %span Sabah
          %li
            = link_to search_people_path(state: "Sarawak") do
              %span Sarawak
          %li
            = link_to search_people_path(state: "Kuala Lumpur") do
              %span Kuala Lumpur
          %li
            = link_to search_people_path(state: "Putrajaya") do
              %span Putrajaya
          %li
            = link_to search_people_path(state: "Labuan") do
              %span Labuan

.clearfix